---
- hosts: rails-app1
  become: yes
  become_method: sudo
  remote_user: root
  gather_facts: no

  # roles:
  #   - { role: "zzet.rbenv" }

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - build-essential
        # - git-core
        # - curl
        # - libxml2-dev
        # - libxslt1-dev
        # - libreadline-dev
        # - libyaml-dev
        # - libcurl4-openssl-dev
        # - libncurses5-dev
        # - libgdbm-dev
        # - libffi-dev
        # - runit
        # - postgresql-9.3
        # - libpq-dev
        # - nodejs

    - name: create user
      user:
        name: deploy
        createhome: yes
        shell: /bin/bash
        group: root
        generate_ssh_key: yes

    - name: copy my ssh key
      authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        user: deploy
        state: present
