---
- name: Configure server to run Nginx, MySQL, Ruby, and serve Rails/Rack apps with Unicorn over SSL
  hosts: rails-app1
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/vault.yml
    - vars/main.yml

  roles:
    - common
    - zzet.rbenv
    - geerlingguy.mysql
    - geerlingguy.nginx
    - nginx_ssl
    - rails
    - static
