---
- name: configure server to run rails/rack apps with Nginx and Unicorn
  hosts: rails-app1
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/vault.yml
    - vars/main.yml

  roles:
    - common
    - zzet.rbenv
    - geerlingguy.mysql
    - geerlingguy.nginx
    - rails
