---
- name: configure server to run rack apps
  hosts: rails-app1
  remote_user: root
  gather_facts: true

  pre_tasks:
    - name: install python2
      raw: sudo apt-get -y install python-simplejson

  vars:
    rbenv:
      env: user
      version: v1.0.0
      ruby_version: 2.3.1
    rbenv_users:
      - deploy

  roles:
    - common
    - zzet.rbenv
