---
- name: Configure server to run Nginx, MySQL, Redis, Ruby, and serve Rails/Rack apps with Puma over SSL
  hosts: rails-app1
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/vault.yml
    - vars/main.yml

  roles:
    - common
    # - andrewsomething.do-agent
    # - zzet.rbenv
    # - geerlingguy.mysql
    # - geerlingguy.redis
    # - geerlingguy.nginx
    # - nginx_ssl
    # - rails
    - static
