---
- name: configure server to run rack apps
  hosts: rails-app1
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: install python2
      raw: sudo apt-get -y install python-simplejson

  roles:
    - common
    - zzet.rbenv
    - geerlingguy.mysql
    - geerlingguy.nginx
