---
- name: Configure a server for Rails/Rack apps
  hosts: rails-app1
  remote_user: root
  gather_facts: no

  pre_tasks:
    - name: Force install python2
      raw: sudo apt-get -y install python-simplejson

  roles:
  - common
