---
- name: configure server for mail with Postfix
  hosts: mail1
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/vault.yml
    - vars/main.yml

  roles:
    - common
    - zzet.rbenv
    - geerlingguy.postfix
