---
- name: install gem dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - imagemagick
    - libmagickwand-dev
    - libmysqlclient-dev

- name: create root {{ rails_app_root }} directory
  file:
    path: "{{ rails_app_root }}"
    state: directory
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create app root directory
  with_items: "{{ rails_apps }}"
  file:
    path: "{{ rails_app_root }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create convenience symlink in home to {{ rails_app_root }} directory
  file:
    src: "{{ rails_app_root }}"
    dest: "/home/{{ rails_app_user }}/apps"
    owner: "{{ rails_app_user }}"
    state: link

- name: create app config directory
  with_items: "{{ rails_apps }}"
  file:
    path: "{{ rails_app_root }}/{{ item }}/shared/config"
    state: directory
    recurse: true
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create files from vault
  with_subelements:
    - "{{ vault_rails }}"
    - "yaml_files"
  no_log: true
  copy:
    dest: "{{ rails_app_root }}/{{ item.0.name }}/shared/config/{{ item.1.filename }}"
    content: "{{ item.1.content | to_nice_yaml }}"
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create unicorn systemd file
  with_items: "{{ rails_apps }}"
  template:
    src: unicorn.service.j2
    dest: "/etc/systemd/system/unicorn-{{ item }}.service"
    owner: root
    group: root
    mode: 0755

- name: update systemd to detect new unicorn configs
  shell: "systemctl daemon-reload"
  become: true

- name: enable unicorn for systemd
  with_items: "{{ rails_apps }}"
  shell: "systemctl enable unicorn-{{ item }}.service"
  become: true

- name: create nginx vhost files for rails apps
  with_items: "{{ rails_apps }}"
  copy:
    src: "nginx/{{ item }}.conf"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    mode: 0755
    owner: "{{ rails_app_user }}"
  notify:
    - reload nginx

- name: symlink enabled vhosts for nginx rails apps
  with_items: "{{ rails_apps }}"
  file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    owner: "{{ rails_app_user }}"
    state: link
  notify:
    - reload nginx
