---
- name: install gem dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - imagemagick
    - libmagickwand-dev
    - libmysqlclient-dev

- name: create root {{ rails_app_root }} directory
  file:
    path: "{{ rails_app_root }}"
    state: directory
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create app root directory
  with_items: "{{ rails_apps }}"
  file:
    path: "{{ rails_app_root }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create app config directory
  with_items: "{{ rails_apps }}"
  file:
    path: "{{ rails_app_root }}/{{ item }}/shared/config"
    state: directory
    recurse: true
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create files from vault
  with_subelements:
    - "{{ vault_rails }}"
    - "yaml_files"
  no_log: true
  copy:
    dest: "{{ rails_app_root }}/{{ item.0.name }}/shared/config/{{ item.1.filename }}"
    content: "{{ item.1.content | to_nice_yaml }}"
    mode: 0755
    owner: "{{ rails_app_user }}"
