---
- name: install gem dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - imagemagick
    - libmagickwand-dev
    - libmysqlclient-dev

- name: create root {{ rails_app_root }} directory
  file:
    path: "{{ rails_app_root }}"
    state: directory
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create app root directory
  with_items: "{{ rails_apps }}"
  file:
    path: "{{ rails_app_root }}/{{ item.name }}"
    state: directory
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create app config directory
  with_items: "{{ rails_apps }}"
  file:
    path: "{{ rails_app_root }}/{{ item.name }}/shared/config"
    state: directory
    recurse: true
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create database.yml files
  with_items: "{{ rails_apps }}"
  when: item.database is defined
  no_log: true
  template:
    src: database_mysql.yml.j2
    dest: "{{ rails_app_root }}/{{ item.name }}/shared/config/database.yml"
    mode: 0755
    owner: "{{ rails_app_user }}"

- name: create secrets.yml files
  with_items: "{{ rails_apps }}"
  when: item.secrets is defined
  no_log: true
  template:
    src: secrets.yml.j2
    dest: "{{ rails_app_root }}/{{ item.name }}/shared/config/secrets.yml"
    mode: 0755
    owner: "{{ rails_app_user }}"
