---
- name: install packages with apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - git-core
    - curl
    - libxml2-dev
    - libxslt1-dev
    - libreadline-dev
    - libffi-dev
    - libssl-dev
    - libyaml-dev

- name: create deploy user
  user:
    name: deploy
    createhome: yes
    shell: /bin/bash
    group: root
    groups: admin,adm
    generate_ssh_key: yes

- name: no password for admin in sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'

- name: prevent the sudo warning
  file:
    path: /home/deploy/.sudo_as_admin_successful
    state: touch

- name: copy ssh public key to deploy user
  authorized_key:
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    user: deploy
    state: present
