---
- name: install packages with apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - git-core
    - curl
    - libxml2-dev
    - libxslt1-dev
    - libreadline-dev
    - libffi-dev
    - libssl-dev
    - libyaml-dev
    - fail2ban

- name: create deploy user
  user:
    name: deploy
    createhome: yes
    shell: /bin/bash
    group: root
    groups: admin,adm
    generate_ssh_key: yes

- name: no password for admin in sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'

- name: prevent the sudo warning
  file:
    path: /home/deploy/.sudo_as_admin_successful
    state: touch

- name: copy ssh public key to deploy user
  authorized_key:
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    user: deploy
    state: present

- name: "UFW incoming deny"
  ufw:
    direction: incoming
    policy: deny

- name: "UFW outgoing allow"
  ufw:
    direction: outgoing
    policy: allow

- name: "UFW allow port 22"
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: "UFW allow port 80"
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: "UFW allow port 443"
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: "UFW logging"
  ufw:
    logging: on

- name: "Enable UFW"
  ufw:
    state: enabled
