---
- name: "install letsencrypt certbot with apt"
  apt:
    state: present
    update_cache: yes
    pkg:
      - certbot
      - python-certbot-nginx

- name: "create ssl-params.conf snippet"
  copy:
    src: "ssl-params.conf"
    dest: /etc/nginx/snippets/
    mode: 0755
    owner: "{{ app_user }}"

- name: "cron entry to renew reload nginx after renewal"
  become: true
  cron:
    name: "reload nginx"
    minute: "18"
    hour: "2,14"
    job: "/bin/systemctl reload nginx"
