---
- name: "install letsencrypt with apt"
  apt:
    state: present
    update_cache: yes
    pkg:
      - letsencrypt

- name: "create ssl-params.conf snippet"
  copy:
    src: "ssl-params.conf"
    dest: /etc/nginx/snippets/
    mode: 0755
    owner: "{{ app_user }}"

- name: "cron entry to renew letsencrypt SSL certs"
  become: true
  cron:
    name: "renew letsencrypt"
    minute: "12"
    hour: "2,14"
    job: "/usr/bin/letsencrypt renew >> /var/log/letsencrypt-renew.log"

- name: "cron entry to renew reload nginx after renewal"
  become: true
  cron:
    name: "reload nginx"
    minute: "18"
    hour: "2,14"
    job: "/bin/systemctl reload nginx"
